language: go

service:
  - docker

go:
  - 1.x

script:
  - go test -v ./...
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "login successful if u see docker images below this..."
  - docker images
  - docker build -t jaykhare/jaydockerrepo:travisimage .
  - echo "Printing image list should contain newly built travis image"
  - docker images
  - docker run -it jaykhare/jaydockerrepo:travisimage
  - docker push jaykhare/jaydockerrepo:travisimage
