language: go

service:
  - docker

go:
  - 1.x

before_install:
  - docker build -t jaykhare/jaydockerrepo .
  - docker run -it jaykhare/jaydockerrepo

script:
  - go test -v ./...

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master
