  
language: go

service:
  - docker

go:
  - 1.x

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  

script:
  - go test -v ./...
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$ HEROKU_PASSWORD" | docker login -u "$ HEROKU_USERNAME" --password-stdin registry.heroku.com
  - echo "login successful if u see docker images below this..."
  - docker images
  - docker build -t jaykhare/jaydockerrepo:travisimage .
  - echo "Printing image list should contain newly built travis image"
  - docker images
  - docker run -it jaykhare/jaydockerrepo:travisimage
  - docker push jaykhare/jaydockerrepo:travisimage
